### ISSUE TITLE
aws-otel-nodejs-ver-1-2-0

### ISSUE THREAD

**Issue by twillzy** [aws-observability/aws-otel-lambda#120]
I've referred to the [doc](https://aws-otel.github.io/docs/getting-started/lambda/lambda-js#add-the-arn-of-the-lambda-layer) but this lambda does not seem to be available from `ap-southeast-2`

When I run
```
aws lambda get-layer-version \
    --layer-name "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-ver-0-23-0" \
    --version-number 1
```

I get this error:
```
An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-ver-0-23-0:1
```

But no issue with python version
```
aws lambda get-layer-version \
    --layer-name "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-python38-ver-1-2-0" \
    --version-number 1
```

**Comment by anuraaga** [comment]
Hi @twillzy - I wonder if you looked at the doc for the Java layer? The layer name for nodejs looks like `arn:aws:lambda:\<region>:901920570463:layer:aws-otel-nodejs-ver-0-23-0:1` (ver-0-23-0, not ver-1-2-0). I couldn't find mention of ver-1-2-0 on the linked doc.

**Comment by twillzy** [comment]
![Screen Shot 2021-07-13 at 5 24 11 pm](https://user-images.githubusercontent.com/2046325/125409341-2614e000-e3ff-11eb-8542-25eac43f019a.png)
Hi @anuraaga, I tried version 1-2-0 but it gives the same error.

```
aws lambda get-layer-version \
    --layer-name "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-ver-1-2-0" \
    --version-number 1
```

**Comment by anuraaga** [comment]
@twillzy Sorry I'm still not following - that screenshot shows `aws-otel-nodejs-ver-0-23-0`. Where are you getting the `ver-1-2-0` string from?

**Comment by twillzy** [comment]
@anuraaga sorry! I pasted the wrong command.

This is the one I ran.

```
aws lambda get-layer-version \
    --layer-name "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-ver-0-23-0" \
    --version-number 1

An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User:  is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-ver-0-23-0:1
```

**Comment by anuraaga** [comment]
Thanks @twillzy for confirming. Looked into our code and found that there seems to be something wrong with the string in the docs (or more accurately our publishing which isn't matching our other language conventions)

https://github.com/aws-observability/aws-otel-lambda/blob/main/sample-apps/nodejs-aws-sdk-terraform/layer.tf#L3

The nodejs ones weren't published with the `ver-` string inside them. @NathanielRN @wangzlei 

Can you copy from that file and try?

**Comment by twillzy** [comment]
Thanks @anuraaga!!

This works:
```
aws lambda get-layer-version \
    --layer-name "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-0-23-0" \
    --version-number 1
```

**Comment by NathanielRN** [comment]
@twillzy Sorry for the inconvenience and thank you for reporting this! You should be able to use the expected `aws-otel-nodejs-ver-0-23-0` name now that we merged #121 🙂

**Comment by nbcchen** [comment]
It still shows `-ver-1-9-1` from [the docs](https://aws-otel.github.io/docs/getting-started/lambda/lambda-js#add-the-arn-of-the-lambda-layer). What would be the latest version of the layer?
